### ISSUE TITLE
1.0.2 is not available in public Maven repos

### ISSUE THREAD

**Issue by AlainODea** [egulias/EmailValidator4J#9]
Can you publish v1.0.2 to a public Maven repo so it can be added as a dependency?

**Comment by egulias** [comment]
Done. Please confirm and close the issue.

**Comment by AlainODea** [comment]
Thank you very much, @egulias. I really appreciate it.

Confirmed with an uprev and some unit tests around my original issue in my dependent project.

Confirmed that the artifacts are publicly hosted in JCenter:
https://jcenter.bintray.com/com/egulias/EmailValidator4J/1.0.2/
https://bintray.com/egulias/maven/EmailValidator4J/1.0.2

**Comment by egulias** [comment]
You are welcome @AlainODea , happy to help.
